version: "3.9"

services:
  web:
    build: .
    working_dir: /app
    entrypoint: ["/app/bin/docker-entrypoint"]
    command: ["./bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PATH=/app/bin:$PATH
      - RAILS_ENV=development
    depends_on:
      db:
        condition: service_healthy

  type_labo:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - ./type_labo:/app
      - frontend-node-modules:/app/node_modules
    # Uncomment if the frontend should wait for backend
    # depends_on:
    #   - web

  db:
    image: mysql:8.0.43
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_development
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 2s
      retries: 20

volumes:
  bundle:
  mysql-data:
  frontend-node-modules:
