---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/health_check":
    get:
      summary: ヘルスチェック
      tags:
      - Health
      security: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                - status
                properties:
                  status:
                    type: string
                    enum:
                    - ok
servers:
- url: http://localhost:3000
  variables:
    defaultHost:
      default: www.example.com
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
- bearerAuth: []
