# MySQL. Versions 5.6.4 and up are supported.
#
# Install the MySQL driver
#   gem install trilogy
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem "trilogy"
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  adapter: trilogy
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USERNAME") { 'db_user' } %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") { 'password' } %>
  port: <%= ENV.fetch("MYSQL_PORT") { '3306' } %>
  charset: utf8mb4
  collation: utf8mb4_bin


development:
  primary:
    <<: *default
    database: app_development
    host: <%= ENV.fetch("MYSQL_HOST") { '127.0.0.1' } %>
  primary_replica:
    <<: *default
    database: app_development
    host: <%= ENV.fetch("MYSQL_READONLY_HOST", ENV.fetch("MYSQL_HOST", "127.0.0.1")) %>
    replica: true
    username: <%= ENV.fetch("MYSQL_READONLY_USER", ENV.fetch("MYSQL_USER", "db_user")) %>
    password: <%= ENV.fetch("MYSQL_READONLY_PASSWORD", ENV.fetch("MYSQL_PASSWORD", "password")) %>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  primary:
    <<: *default
    database: app_test
    host: <%= ENV.fetch("MYSQL_HOST") { '127.0.0.1' } %>
  primary_replica:
    <<: *default
    database: app_test
    host: <%= ENV.fetch("MYSQL_READONLY_HOST", ENV.fetch("MYSQL_HOST", "127.0.0.1")) %>
    replica: true
    username: <%= ENV.fetch("MYSQL_READONLY_USER", ENV.fetch("MYSQL_USER", "db_user")) %>
    password: <%= ENV.fetch("MYSQL_READONLY_PASSWORD", ENV.fetch("MYSQL_PASSWORD", "password")) %>

# As with config/credentials.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password or a full connection URL as an environment
# variable when you boot the app. For example:
#
#   DATABASE_URL="mysql2://myuser:mypass@localhost/somedatabase"
#
# If the connection URL is provided in the special DATABASE_URL environment
# variable, Rails will automatically merge its configuration values on top of
# the values provided in this file. Alternatively, you can specify a connection
# URL environment variable explicitly:
#
#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>
#
# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.
#
production:
  primary: &primary_production
    <<: *default
    database: app_production
    username: app
    password: <%= ENV["APP_DATABASE_PASSWORD"] %>
  primary_replica:
    <<: *default
    database: app_production
    host: <%= ENV.fetch("MYSQL_READONLY_HOST", ENV.fetch("MYSQL_HOST", "127.0.0.1")) %>
    replica: true
    username: <%= ENV.fetch("MYSQL_READONLY_USER", ENV.fetch("MYSQL_USER", "db_user")) %>
    password: <%= ENV.fetch("MYSQL_READONLY_PASSWORD", ENV.fetch("MYSQL_PASSWORD", "password")) %>
